In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
from PIL import Image
import numpy as np

def image_to_matrix(image_path):
    with Image.open(image_path) as img:
        # Convert image to grayscale ('L' mode)
        img_gray = img.convert('L')

        # Convert image to a numpy array (matrix of pixel values)
        img_matrix = np.array(img_gray)

        return img_matrix

def print_matrix(matrix):
    for row in matrix:
        print(' '.join(f'{pixel:3}' for pixel in row))

image_path = '/content/drive/MyDrive/Classroom/Machine Learning- CS307/spaceship.jpg'

matrix = image_to_matrix(image_path)
print_matrix(matrix)

 12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  11  14   9  13  17  10  12  13  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  12  13  13  12  13  14  14  13  13  13  13  12  16  21  21  17  13  12  14  13  13  13  13  13  13  13  13  14  13  12  11  12  14  18  20  14  14  14  14  14  14  14  14  14  14  14  14  14  14  14  14  13  17  14  22   7  14  40   4  17  16  16  16  16  15  15  15  14  14  14  14  14  14  14  14  14  14  14  14  14  14  13  12  12  18   8  16  67  15  19  20  14  14  14  14  14  14  14  14  14  14  14  14  14  14  14  14  15  15  15  15  15  15  15  16  17  17  17  17  17  17  17  17  19  19  19  19  19  19  19  19  20  20  20  20  20  20  20  20  21  15  12  15  20  21  21  22  20  20  20  20  20  20  20  20  19  19  19  19  19  19  19  19  21  21  21  21  21  21  21  21  21  21  21  21  21  21  21  21  22  22  22  22  22  22  21  21  19  19  18  18  17  18  20  22  23  23  23  23  23  23  23  23  23  23 

In [3]:
import numpy as np

def build_vocab(text):
    # Create a set of unique characters
    unique_chars = sorted(set(text))
    # Create a mapping from character to index
    char_to_index = {char: idx for idx, char in enumerate(unique_chars)}
    return char_to_index

def text_to_one_hot(text, char_to_index):
    # Initialize an empty list for one-hot vectors
    one_hot_vectors = []
    vocab_size = len(char_to_index)

    for char in text:
        # Create a zero vector of length vocab_size
        one_hot_vector = np.zeros(vocab_size, dtype=int)
        # Set the appropriate index to 1
        if char in char_to_index:
            index = char_to_index[char]
            one_hot_vector[index] = 1
        one_hot_vectors.append(one_hot_vector)

    return np.array(one_hot_vectors)

def print_one_hot_vectors(one_hot_vectors):
    # Print the one-hot vectors
    for vector in one_hot_vectors:
        print(vector)

# Sample text
text = "This is sample text."

# Build vocabulary from the text
char_to_index = build_vocab(text)

# Convert text to one-hot vectors
one_hot_vectors = text_to_one_hot(text, char_to_index)

# Print one-hot vectors
print_one_hot_vectors(one_hot_vectors)

[0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0]


In [4]:
!pip install opencv-python numpy


import cv2
import numpy as np

def video_to_frames(video_path):
    cap = cv2.VideoCapture(video_path)
    frames = []

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(frame)

    cap.release()
    return frames

def frames_to_matrix(frames):
    if not frames:
        return np.array([])

    # Convert first frame to grayscale to determine dimensions
    first_frame = cv2.cvtColor(frames[0], cv2.COLOR_BGR2GRAY)
    height, width = first_frame.shape
    num_frames = len(frames)

    # Initialize the matrix
    video_matrix = np.zeros((num_frames, height, width), dtype=np.uint8)

    for i, frame in enumerate(frames):
        # Convert frame to grayscale
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        # Store in the matrix
        video_matrix[i] = gray_frame

    return video_matrix

def print_video_matrix(video_matrix, num_frames=5):
    # Print a small portion of the video matrix for readability
    for i in range(min(num_frames, video_matrix.shape[0])):
        print(f'Frame {i}:')
        print(video_matrix[i])
        print()

video_path = '/content/drive/MyDrive/Classroom/Machine Learning- CS307/video.mp4'

# Extract frames from the video
frames = video_to_frames(video_path)

# Convert frames to a 4D matrix (num_frames, height, width)
video_matrix = frames_to_matrix(frames)

# Print a small portion of the video matrix
print_video_matrix(video_matrix)

Frame 0:
[[200 200 200 ... 207 207 207]
 [200 200 200 ... 207 207 207]
 [200 200 200 ... 207 207 207]
 ...
 [ 75  81  90 ...  30  29  32]
 [ 75  83  95 ...  28  28  32]
 [ 71  69  76 ...  29  29  31]]

Frame 1:
[[200 200 200 ... 207 207 207]
 [200 200 200 ... 207 207 207]
 [200 200 200 ... 207 207 207]
 ...
 [ 78  85  94 ...  35  31  31]
 [ 75  82  93 ...  33  30  30]
 [ 71  71  76 ...  32  29  30]]

Frame 2:
[[200 200 200 ... 207 207 207]
 [200 200 200 ... 207 207 207]
 [200 200 200 ... 207 207 207]
 ...
 [ 77  84  96 ...  38  37  33]
 [ 74  79  90 ...  36  35  32]
 [ 69  69  76 ...  36  32  30]]

Frame 3:
[[201 201 201 ... 207 207 207]
 [201 201 201 ... 207 207 207]
 [201 201 201 ... 207 207 207]
 ...
 [ 78  85 100 ...  42  39  39]
 [ 73  75  86 ...  42  39  39]
 [ 68  69  76 ...  40  39  38]]

Frame 4:
[[200 200 200 ... 207 207 207]
 [200 200 200 ... 207 207 207]
 [200 200 200 ... 207 207 207]
 ...
 [ 78  82 100 ...  44  42  39]
 [ 74  69  82 ...  46  43  40]
 [ 69  65  78 ...  46  